name: Build and Deploy
on:
  push:
    branches: [main, master]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout  ️
        uses: actions/checkout@v4

      - name: lock npm version
        uses: actions/setup-node@v4
        with:
          node-version: 18.14.0

      - name: Install and Build
        run: |
          npm i -g pnpm
          pnpm run init
          pnpm run docs:build
        env:
          NODE_OPTIONS: '--max_old_space_size=4096 --openssl-legacy-provider'

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: docs/.vuepress/dist
          token: ${{ secrets.ACCESS_TOKEN }}
